// Code generated by MockGen. DO NOT EDIT.
// Source: internal/service/cardvalidator/service.go
//
// Generated by this command:
//
//	mockgen -source=internal/service/cardvalidator/service.go -destination=internal/service/cardvalidator/mock/mock_cardvalidator.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	cardvalidator "card-validator-api/internal/service/cardvalidator"
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockCardValidator is a mock of CardValidator interface.
type MockCardValidator struct {
	ctrl     *gomock.Controller
	recorder *MockCardValidatorMockRecorder
	isgomock struct{}
}

// MockCardValidatorMockRecorder is the mock recorder for MockCardValidator.
type MockCardValidatorMockRecorder struct {
	mock *MockCardValidator
}

// NewMockCardValidator creates a new mock instance.
func NewMockCardValidator(ctrl *gomock.Controller) *MockCardValidator {
	mock := &MockCardValidator{ctrl: ctrl}
	mock.recorder = &MockCardValidatorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCardValidator) EXPECT() *MockCardValidatorMockRecorder {
	return m.recorder
}

// Validate mocks base method.
func (m *MockCardValidator) Validate(ctx context.Context, req *cardvalidator.CardValidationRequest) (*cardvalidator.CardValidationResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Validate", ctx, req)
	ret0, _ := ret[0].(*cardvalidator.CardValidationResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Validate indicates an expected call of Validate.
func (mr *MockCardValidatorMockRecorder) Validate(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Validate", reflect.TypeOf((*MockCardValidator)(nil).Validate), ctx, req)
}
